apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-rc
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: itwb/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: userdb
        - name: MYSQL_USER
          value: itwb
        - name: MYSQL_PASSWORD
          value: itwb
        ports:
        - containerPort: 3306
