apiVersion: v1
kind: Pod
metadata:
  name: jws-pod
  labels: 
    name: jws
spec: 
  containers: 
    - image: jws3-rhel7
      name: jws-pod
      livenessProbe:
        # an http probe
        httpGet:
          path: /node-info/
          port: 8080
        # length of time to wait for a pod to initialize
        # after pod startup, before applying health checking
        initialDelaySeconds: 30
        timeoutSeconds: 5
      ports: 
        - containerPort: 8080
