apiVersion: v1
kind: ReplicationController
metadata:
  name: jws-rc
spec:
  replicas: 2
  selector:
    app: jws
  template:
    metadata:
      labels:
        app: jws
    spec:
      containers:
      - name: jws
        image: jws3-rhel7
        ports:
          - name: jws
            containerPort: 8080
