apiVersion: v1
kind: ReplicationController
metadata:
  name: wildfly-custom-rc
  labels:
    name: wildfly-custom
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: wildfly-custom
    spec:
      containers:
      - name: wildfly-custom-pod
        image: wildfly-custom
        ports:
        - containerPort: 8080
